stages:
  - lint
  - validate
  - dry-run
  - render-and-commit

# Lint básico de YAMLs con yamllint
lint-yaml:
  stage: lint
  image:
    name: cytopia/yamllint:alpine
    entrypoint: [""]
  tags:
    - aether-runner
  script:
    - yamllint -c .yamllint deps/5gc/roles/core/templates/sdcore-5g-values.yaml

  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main")'
    when: always

# Validar sintaxis con yq
validate-values-syntax:
  stage: validate
  image: 192.168.12.15:8083/yq-go-alpine:3.19
  tags:
    - aether-runner
  # before_script:
  #   - apk add --no-cache git bash wget
  #   - wget -qO /usr/local/bin/yq-go https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
  #   - chmod +x /usr/local/bin/yq-go
  script:
    - echo "Validando sintaxis de values.yaml"
    - yq-go e . deps/5gc/roles/core/templates/sdcore-5g-values.yaml >/dev/null
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main")'
    when: always


helm-dry-run-on-mr:
  stage: dry-run
  tags:
    - aether-runner
  image: 192.168.12.15:8083/onramp-render-template:1.0
  # before_script:
  #   - pip install --quiet "ansible<11"
  #   - apt-get update && apt-get install -y curl git
  #   - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  script:
    # Definir la ruta absoluta para el archivo temporal
    #  $CI_PROJECT_DIR para garantizar que la ruta es inequívoca.
    - TEMP_VALUES_PATH="${CI_PROJECT_DIR}/temp_values_for_validation.yaml"
    - echo "Se generará el archivo de validación en:" ${TEMP_VALUES_PATH}
    # Renderizar la plantilla de Helm values en un archivo temporal
    - echo "Renderizando plantilla para validación..."
    - |
      ansible-playbook deps/5gc/core.yml \
      --inventory localhost, \
      --connection local \
      -e @vars/main.yml \
      --tags "gitops_render_values" \
      --extra-vars "output_path=${TEMP_VALUES_PATH}"

    # Añadir repos de Helm y validar
    - echo "Validando con Helm..."
    - helm repo add aether https://charts.aetherproject.org
    - helm repo update

    # Descargar y descomprimir el chart en el directorio local --
    # El flag --untar es crucial. Creará un directorio llamado 'sd-core' en el workspace.
    - echo "Descargando el chart 'aether/sd-core' localmente..."
    - helm pull aether/sd-core --version 3.0.0 --untar

    # Linter y template. Helm usará el values TEMPORAL RENDERIZADO.
    - helm lint ./sd-core --values ${TEMP_VALUES_PATH}
    - helm template sd-core ./sd-core --version 3.0.0 --values ${TEMP_VALUES_PATH} > /dev/null

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main")'

      when: always


render-and-commit-gitops-values:
  stage: render-and-commit
  needs:
    - lint-yaml
    - validate-values-syntax
    - helm-dry-run-on-mr
  tags:
    - aether-runner
  image: 192.168.12.15:8083/onramp-render-template:1.0
  # before_script:
  #   - pip install --quiet "ansible<11"
  #   - apt update && apt install git -y
  script:
    # Configuración de Git 
    - echo "Configuring Git user..."
    - git config --global user.email "ci-bot@aether.local"
    - git config --global user.name "CI Bot"
    # Usamos CI_JOB_TOKEN para autenticarnos y poder hacer push
    - git remote set-url origin "https://$TOKEN_USER:$ONRAMP_TOKEN@$GITLAB_SERVER_URL/5g/aether.git"

    # Preparar variables y rutas 
    - ENV_DIR="${CI_PROJECT_DIR}/environments/${CI_COMMIT_BRANCH}"
    - OUTPUT_FILE="${ENV_DIR}/5g-core-values.yaml"
    - echo "Rendering values for branch '${CI_COMMIT_BRANCH}' into '${OUTPUT_FILE}'"
    - mkdir -p ${ENV_DIR}

    # Ejecutar Ansible para renderizar la plantilla
    # Usamos el mismo comando que en el dry-run, pero ahora guardamos en la ruta permanente
    - |
      ansible-playbook deps/5gc/core.yml \
      --inventory localhost, \
      --connection local \
      -e @vars/main.yml \
      --tags "gitops_render_values" \
      --extra-vars "output_path=${OUTPUT_FILE}"

    # Commitear y pushear los cambios si los hay ---
    - echo "Checking for changes in the rendered file..."
    - git add ${OUTPUT_FILE}
    - |
      if git diff --staged --quiet; then
        echo "No changes detected in Helm values. Nothing to commit."
      else
        echo "Helm values changed. Committing and pushing back to '${CI_COMMIT_BRANCH}'..."
        # El [skip ci] es VITAL para evitar que este push dispare otro pipeline.
        git commit -m "chore(ci): Render Helm values for ${CI_COMMIT_BRANCH} [skip ci]"
        git push origin HEAD:${CI_COMMIT_BRANCH}
      fi

  rules:
    # el job SÓLO se ejecuta en un push (como un merge) a las ramas de entorno, y NO en los MRs.
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main")'
#    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "main")'


