[all]
node1 ansible_host=192.168.12.11 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abelct/.ssh/id_rsa # Single Node of Quick Start Deployment (Initial version)
#node1 ansible_host=192.168.12.11 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abelct/.ssh/id_rsa # Master Node multi VM desployment
node2 ansible_host=192.168.12.13 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abelct/.ssh/id_rsa # Node for UERANSIM
#node3 ansible_host=192.168.12.14 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abelct/.ssh/id_rsa
#node4 ansible_host=192.168.12.15 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abelct/.ssh/id_rsa

[master_nodes]
node1

[worker_nodes]
#node2
#node3

[gnbsim_nodes]
#node1
#node2
#node4

[oai_nodes]
#node2
#node4

[ueransim_nodes]
node2
#node4

[srsran_nodes]
#node2
#node4
