{
 "title": "5G Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "5G Active PDU Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smf_pdu_sessions{service=\"metricfunc\"}"
    }
   ]
  },
  {
   "title": "UPF Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"UPF\"}",
     "legendFormat": "{{ Nfname }}"
    }
   ]
  },
  {
   "title": "gNodeB Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"GNB\"}",
     "legendFormat": "{{ Nfname }}"
    }
   ]
  },
  {
   "title": "5G Core Subscribers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(core_subscriber) by (imsi, slice, ip_addr, state)"
    },
    {
     "expr": "sum without (id) (label_replace(smf_pdu_session_profile, \"imsi\", \"$1\", \"id\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "UPF Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Upstream Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Access\"}[2m]))",
     "legendFormat": "Downstream Bitrate"
    }
   ]
  },
  {
   "title": "UPF Subscribers Upload Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_session_tx_bytes{namespace=\"aether-5gc\",pdr=~\".*[13579]\"}[2m])) by (ue_ip)",
     "legendFormat": "{{ue_ip}}"
    }
   ]
  },
  {
   "title": "UPF Subscribers Download Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_session_tx_bytes{namespace=\"aether-5gc\",pdr=~\".*[02468]\"}[2m])) by (ue_ip)",
     "legendFormat": "{{ue_ip}}"
    }
   ]
  }
 ]
}