apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-aether-apps
  namespace: argocd
spec:
  project: default
  source:
    # Apunta a la URL del MIRROR PÚBLICO.
    repoURL: https://github.com/networkgcorefullcode/aether-onramp

    #  Apunta a la rama y la carpeta donde viven los manifiestos de las apps.
    targetRevision: dev
    path: apps/operator

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      