apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sd-core
  namespace: argocd
spec:
  # El proyecto por defecto donde viven los recursos de la App
  project: default

  # SECCIÓN 'source' PRINCIPAL
  sources:
    # El repositorio de Helm que contiene el CHART de aetherproject
#    - chart: sd-core
#      repoURL: https://charts.aetherproject.org
#      targetRevision: 3.0.0
#      helm:
#        valueFiles:
#          - $values-from-git/environments/operator/5g-core-operator-values.yaml
        # postRenderer:
        #   command: ["./helm-patches/webui/post-render.sh"]
    - repoURL: ghcr.io/networkgcorefullcode  ## registro propio
      chart: sd-core
      targetRevision: 3.1.9
      helm:
        valueFiles:
          - $values-from-git/environments/operator/5g-core-operator-values.yaml
        # postRenderer:
        #   command: ["./helm-patches/webui/post-render.sh"]


      # El repositorio público que contiene los VALUES.YAML
    - repoURL: https://github.com/networkgcorefullcode/aether-onramp.git
      # La rama que debe observar en el repo PÚBLICO
      targetRevision: dev
      ref: values-from-git

  destination:
    # Apunta al clúster donde este instalado Argo CD
    server: 'https://kubernetes.default.svc'
    # El namespace donde se despliegan los recursos del 5G Core
    namespace: aether-5gc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
