---

- name: install argocd
  import_tasks: roles/argocd/tasks/install.yml
  tags: install
  when: inventory_hostname in groups['master_nodes'] or inventory_hostname in groups['worker_nodes']


- name: uninstall argocd
  import_tasks: roles/argocd/tasks/uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['master_nodes'] or inventory_hostname in groups['worker_nodes']
