---

kubeconfig_path: /home/ubuntu/.kube/config
argocd_manifest_url: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
downloaded_manifest: "/tmp/argocd-install.yaml"
kubectl_bin: /var/lib/rancher/rke2/bin/kubectl
