---
- name: Running uninstall RKE2 script
  become: true
  shell: /usr/local/bin/rke2-uninstall.sh
  register: script_output

- name: Show script output
  debug:
    var: script_output.stdout_lines
# - name: Show script output
#   debug:
#     msg: "{{ script_output.stdout_lines }}"
#   when: script_output.stdout | length > 0

# - name: Show script errors
#   debug:
#     msg: "{{ script_output.stderr_lines }}"
#   when: script_output.stderr | length > 0
