# Este archivo contiene la lógica específica para el renderizado de GitOps
# Es importado por main.yml

- name: "GitOps | Render 5G Core Helm values file"
  ansible.builtin.template:
    src: "sdcore-5g-values.yaml"
    dest: "{{ output_path }}"
  when: output_path is defined
  delegate_to: localhost
  run_once: true
  tags:
    - never
    - gitops_render_values