<<<<<<< HEAD
---
rke2_pod_security_admission_config_file_path: "{{ playbook_dir }}/inventory/storage/files/pod-security-admission-config.yaml"
rke2_audit_policy_config_file_path: "{{ playbook_dir }}/inventory/storage/files/audit-policy.yaml"
rke2_manifest_config_directory: "{{ playbook_dir }}/inventory/storage/pre-deploy-manifests/"
rke2_manifest_config_post_run_directory: "{{ playbook_dir }}/inventory/storage/post-deploy-manifests/"

group_rke2_config:
  cni:
    - multus
    - canal
  disable-kube-proxy: false
  node-label:
    - node-role.aetherproject.org=omec-upf
  service-cidr: 10.43.0.0/16
  cluster-cidr: 10.42.0.0/16
  kubelet-arg:
    - --allowed-unsafe-sysctls=net.*
  #kube-proxy-image: "192.168.12.15:8082/docker-hosted/kube-proxy-new-ipset:ipset-7.23"
  kube-proxy-arg:
    - --metrics-bind-address=0.0.0.0:10249
    - --proxy-mode=ipvs
  kube-proxy-image: 192.168.12.15:8083/kube-proxy-new-ipset:ipset-7.23.v4
  # kube-proxy-image: ghcr.io/networkgcorefullcode/omecproject/kube-proxy-new-ipset:ipset-7.23.v4
  #- --feature-gates=RemoveSelfLink=false
  #- --v=4
  #- --ipvs-strict-arp=true
  #- --feature-gates=SCTPSupport=true
  #- --enable-sctp-support=true
  ###
  #para modo iptables
  #- --conntrack-max-per-core=131072 # Aumentar conexiones concurrentes (N2/N4)
  #- --iptables-sync-period=30s      # Sincronización más frecuente
  kube-apiserver-arg:
    - --service-node-port-range=2000-36767
    #- --feature-gates=SCTPSupport=true
  #selinux: false
  #server: https://192.168.12.16:9345
  pause-image: k8s.gcr.io/pause:3.3
  # Configuración adicional para montar ipset del host
  #kube-proxy-extra-mount:
  #- "/usr/sbin/ipset:/usr/sbin/ipset"
  #- "/lib/modules:/lib/modules"
  #- "/usr/lib:/host/usr/lib"
  #- "/sbin/modprobe:/sbin/modprobe"
=======
---
rke2_pod_security_admission_config_file_path: "{{ playbook_dir }}/inventory/storage/files/pod-security-admission-config.yaml"
rke2_audit_policy_config_file_path: "{{ playbook_dir }}/inventory/storage/files/audit-policy.yaml"
rke2_manifest_config_directory: "{{ playbook_dir }}/inventory/storage/pre-deploy-manifests/"
rke2_manifest_config_post_run_directory: "{{ playbook_dir }}/inventory/storage/post-deploy-manifests/"

group_rke2_config:
  cni:
    - multus
    - canal
  disable-kube-proxy: false
  node-label:
    - node-role.aetherproject.org=omec-upf
  service-cidr: 10.43.0.0/16
  cluster-cidr: 10.42.0.0/16
  kubelet-arg:
    - --allowed-unsafe-sysctls=net.*
  #kube-proxy-image: "192.168.12.15:8082/docker-hosted/kube-proxy-new-ipset:ipset-7.23"
  kube-proxy-arg:
    - --metrics-bind-address=0.0.0.0:10249
    - --proxy-mode=ipvs
  kube-proxy-image: 192.168.12.15:8083/kube-proxy-new-ipset:ipset-7.23.v4
  # kube-proxy-image: ghcr.io/networkgcorefullcode/omecproject/kube-proxy-new-ipset:ipset-7.23.v4
  #- --feature-gates=RemoveSelfLink=false
  #- --v=4
  #- --ipvs-strict-arp=true
  #- --feature-gates=SCTPSupport=true
  #- --enable-sctp-support=true
  ###
  #para modo iptables
  #- --conntrack-max-per-core=131072 # Aumentar conexiones concurrentes (N2/N4)
  #- --iptables-sync-period=30s      # Sincronización más frecuente
  kube-apiserver-arg:
    - --service-node-port-range=2000-36767
    #- --feature-gates=SCTPSupport=true
  #selinux: false
  #server: https://192.168.12.16:9345
  pause-image: k8s.gcr.io/pause:3.3
  # Configuración adicional para montar ipset del host
  #kube-proxy-extra-mount:
  #- "/usr/sbin/ipset:/usr/sbin/ipset"
  #- "/lib/modules:/lib/modules"
  #- "/usr/lib:/host/usr/lib"
  #- "/sbin/modprobe:/sbin/modprobe"
>>>>>>> testing-local
