---
rke2_pod_security_admission_config_file_path: "{{ playbook_dir }}/inventory/storage/files/pod-security-admission-config.yaml"
rke2_audit_policy_config_file_path: "{{ playbook_dir }}/inventory/storage/files/audit-policy.yaml"
rke2_manifest_config_directory: "{{ playbook_dir }}/inventory/storage/pre-deploy-manifests/"
rke2_manifest_config_post_run_directory: "{{ playbook_dir }}/inventory/storage/post-deploy-manifests/"

group_rke2_config:
  cluster-cidr: 10.42.0.0/16
  cni:
    - multus
    - canal
  disable-kube-proxy: false
  kube-proxy-arg:
    - --metrics-bind-address=0.0.0.0:10249
    - --proxy-mode=ipvs
    #- --feature-gates=RemoveSelfLink=false
    - --v=4
    - --ipvs-strict-arp=true
    #- --feature-gates=SCTPSupport=true
    #- --enable-sctp-support=true
    ###
    #para modod iptables
    #- --conntrack-max-per-core=131072 # Aumentar conexiones concurrentes (N2/N4)
    #- --iptables-sync-period=30s      # Sincronización más frecuente
  kubelet-arg:
    - --allowed-unsafe-sysctls=net.*
  kube-apiserver-arg:
    - --service-node-port-range=2000-36767
    #- --feature-gates=SCTPSupport=true
  node-label:
    - node-role.aetherproject.org=omec-upf
  selinux: false
  server: https://192.168.12.16:9345
  service-cidr: 10.43.0.0/16
  pause-image: k8s.gcr.io/pause:3.3
  token: K106c0deb00b24a7f2371f3928ad327fe9e9e65cc1f233d84537b3d7c3237a4616b::server:ee8c1626d190fee5125df248380e38c6
  # Configuración adicional para montar ipset del host
  #kube-proxy-extra-mount:
  #- "/usr/sbin/ipset:/usr/sbin/ipset"
  #- "/lib/modules:/lib/modules"
  #- "/usr/lib:/host/usr/lib"
  #- "/sbin/modprobe:/sbin/modprobe"
