<<<<<<< HEAD
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all-helm-output.yaml

patches:
  - path: webui-svc-patch.yaml 
    target:                   
      kind: Service
      name: webui
=======
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all-helm-output.yaml

patches:
  - path: webui-svc-patch.yaml 
    target:                   
      kind: Service
      name: webui
>>>>>>> testing-local
