apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aether-5g-core-dev
  namespace: argocd
spec:
  # El proyecto por defecto donde viven los recursos de la App
  project: default

  source:
    #  APUNTA A LA URL PÚBLICA
    repoURL: https://github.com/networkgcorefullcode/aether-onramp

    # ESPECIFICA EL NOMBRE DEL CHART Y LA RUTA (Leído del repo público)
    chart: 'sd-core'
   #path: some/path # por ahora no aplica

    # INDICA LA REVISIÓN (Commit SHA o rama, leído del repo público)
    targetRevision: dev

    # Sobrescribe DE DÓNDE sacar los values.yaml
    helm:
      valueFiles:
      # Esto es una sintaxis especial de Argo CD: $<alias-del-proyecto>:<ruta>
      - $onramp-private:environments/dev/5g-core-values.yaml

  destination:
    # Apunta al clúster donde está instalado Argo CD
    server: 'https://kubernetes.default.svc'

    # El namespace donde se despliegan los recursos del 5G Core
    namespace: aether-5gc