vault_version: "1.15.0"
# Get checksum with: ./scripts/get_vault_checksum.sh 1.15.0
vault_checksum: "sha256:45cf99a6118edf4b8cf72fa95db8b70b4c6c09129c74fce4df0b62c4a03f4df6"
vault_user: "vault"
vault_group: "vault"
vault_install_prerequisites:
  - unzip
  - curl
vault_config_path: "/etc/vault.hcl"
vault_data_path: "/opt/vault/data"
vault_address: "http://127.0.0.1:8200"

# Unseal keys and root token storage
unseal_keys_dir_output: "{{ playbook_dir }}/vault_keys/unseal_keys"
root_token_dir_output: "{{ playbook_dir }}/vault_keys/root_token"
